[theme]
base = "light"
primaryColor = "#00aaff"
backgroundColor = "#f9f9f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
font = "sans serif"

# No haré uso de esta configuración ya que no me funcionó.
# [server]
# headless = true
# port = 10000

# [browser]
# serverAddress = "0.0.0.0"
# serverPort = 10000
